Sponsor.create([
  {
    sponsor_name: "National Suicide Prevention Lifeline", 
    sponsor_email: "founder@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "The premier lifeline in the United States.",
    sponsor_website: "www.example.com",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  }, 
  {
    sponsor_name: "Crisis Text Line", 
    sponsor_email: "staff@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "The premier textline in the United States.",
    sponsor_website: "www.example.com",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  }, 
  {
    sponsor_name: "The Trevor Project", 
    sponsor_email: "hey@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "A crisis intervention nonprofit for LGBTQ youth.",
    sponsor_website: "www.example.com",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  },
])

CrisisResource.create([
  {
    crisis_resource_name: "National Suicide Prevention Lifeline", 
    crisis_resource_tagline: "The premier lifeline in the United States.",
    crisis_resource_desc: "The national suicide prevention lifeline is the premier lifeline in the United States, welcoming calls 24/7 for anyone in need.",
    crisis_resource_industry: "Suicide Prevention",
    crisis_resource_category: "Hotline",
    crisis_resource_medium: "Phone",
    crisis_resource_language: "English",
    crisis_resource_hours: "Open 24/7",
    crisis_resource_email: "info@example.com",
    crisis_resource_phone: "1-555-555-5555",
    crisis_resource_coverage: "United States of America",
    sponsor_id: 1
  }, 
  {
    crisis_resource_name: "The Veterans' Crisis Line", 
    crisis_resource_tagline: "The premier lifeline for veterans and active duty military members in the United States.",
    crisis_resource_desc: "The Veterans Crisis Line is a hotline provided by the National Suicide Prevention Lifeline with trained military and military family counselors.",
    crisis_resource_industry: "Suicide Prevention",
    crisis_resource_category: "Hotline",
    crisis_resource_population: "Veterans",
    crisis_resource_medium: "Phone",
    crisis_resource_language: "English",
    crisis_resource_hours: "Open 24/7",
    crisis_resource_email: "info@example.com",
    crisis_resource_phone: "1-555-555-5555p1",
    crisis_resource_coverage: "United States of America",
    sponsor_id: 1
  }, 
  {
    crisis_resource_name: "The Crisis Text Line", 
    crisis_resource_tagline: "The premier lifeline in the United States.",
    crisis_resource_desc: "The national suicide prevention lifeline is the premier lifeline in the United States, welcoming calls 24/7 for anyone in need.",
    crisis_resource_industry: "Suicide Prevention",
    crisis_resource_category: "Textline",
    crisis_resource_medium: "SMS",
    crisis_resource_language: "English",
    crisis_resource_hours: "Open 24/7",
    crisis_resource_email: "info@example.com",
    crisis_resource_sms: "741-741",
    crisis_resource_coverage: "United States of America",
    sponsor_id: 2
  },
  {
    crisis_resource_name: "The Trevor Lifeline", 
    crisis_resource_tagline: "The premier lifeline for LGBTQ youth in the USA.",
    crisis_resource_desc: "The trevor project is a crisis hotline for .",
    crisis_resource_industry: "Suicide Prevention",
    crisis_resource_category: "Hotline",
    crisis_resource_medium: "SMS",
    crisis_resource_language: "English",
    crisis_resource_hours: "Open 24/7",
    crisis_resource_email: "info@example.com",
    crisis_resource_phone: "855-555-5555",
    crisis_resource_coverage: "United States of America",
    sponsor_id: 3
  },
])