# SPONSORS

sponsor1 = Sponsor.create({
    sponsor_name: "The National Suicide Prevention Lifeline", 
    sponsor_email: "founder@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "The premier lifeline in the United States.",
    sponsor_desc: "We can all help prevent suicide. The Lifeline provides 24/7, free and confidential support for people in distress, prevention and crisis resources for you or your loved ones, and best practices for professionals.",
    sponsor_url_to_logo: "https://suicidepreventionlifeline.org/wp-content/themes/lifeline/assets/icons/logo.png",
    sponsor_website: "http://www.suicidepreventionlifeline.org",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  })

sponsor2 = Sponsor.create({
    sponsor_name: "The Crisis Text Line", 
    sponsor_email: "staff@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "The premier crisis textline provider in the United States.",
    sponsor_desc: "The Crisis Text Line is a global not-for-profit organization providing free crisis intervention via SMS message. The organization's services are available 24 hours a day every day, throughout the US by texting 741741, Canada by texting 686868, and the United Kingdom by texting 85258.",
    sponsor_url_to_logo: nil,
    sponsor_website: "https://www.example.com",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  })

sponsor3 = Sponsor.create({
    sponsor_name: "The Trevor Project", 
    sponsor_email: "hey@example.com",
    password_digest: "thisismypassworddigest",
    sponsor_tagline: "Saving Young LGBTQ Lives.",
    sponsor_desc: nil,
    sponsor_url_to_logo: nil,
    sponsor_website: "https://www.thetrevorproject.org/",
    sponsor_phone: "1-555-555-5555",
    sponsor_address: "4000 Maple Drive",
    sponsor_city: "New York",
    sponsor_region: "NY",
    sponsor_country: "United States of America",
  })


# LISTINGS

listing1 = Listing.create({
  listing_name: "The National Suicide Prevention Lifeline", 
  listing_tagline: "The premier lifeline in the United States.",
  listing_desc: "The National Suicide Prevention Lifeline is the premier lifeline in the United States, welcoming calls 24/7 for anyone in need.",
  listing_industry: "Suicide Prevention",
  listing_category: "Hotline",
  listing_url_to_img: "https://imgur.com/KwVcfVE.png",
  listing_medium: "Phone",
  listing_age: "All Ages",
  listing_population: "All Individuals",
  listing_language: "English, Spanish",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: "1-800-273-8255",
  listing_coverage: "National",
})

listing2 = Listing.create({
  listing_name: "The Veterans' Crisis Line", 
  listing_tagline: "The premier lifeline for veterans and active duty military members in the United States.",
  listing_desc: "The Veterans Crisis Line is a hotline provided by the National Suicide Prevention Lifeline with trained military and military family counselors.",
  listing_industry: "Suicide Prevention",
  listing_category: "Hotline",
  listing_url_to_img: "https://imgur.com/KwVcfVE.png",
  listing_medium: "Phone",
  listing_age: "All Ages",
  listing_population: "Veterans",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: "1-800-273-8255p1",
  listing_sms: nil,
  listing_url: nil,
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United States of America",
  listing_coverage: "National",
})

listing3 = Listing.create({
  listing_name: "The Crisis Text Line", 
  listing_tagline: "Crisis Text Line is the free, 24/7, confidential text message service for people in crisis.",
  listing_desc: "The Crisis Text Line is a global not-for-profit organization providing free crisis intervention via SMS message. The organization's services are available 24 hours a day every day, throughout the US by texting 741741, Canada by texting 686868, and the United Kingdom by texting 85258.",
  listing_industry: "Suicide Prevention",
  listing_category: "Textline",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Texting",
  listing_age: "All Ages",
  listing_population: "All Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: nil,
  listing_sms: "741-741",
  listing_url: nil,
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United States of America",
  listing_coverage: "National",
})

listing4 = Listing.create({
  listing_name: "Trevor Lifeline", 
  listing_tagline: "A national 24-hour, toll free confidential suicide hotline for LGBTQ youth.",
  listing_desc: "Our trained counselors are here to support you 24/7. If you are a young person in crisis, feeling suicidal, or in need of a safe and judgment-free place to talk, call the TrevorLifeline now at 1-866-488-7386.",
  listing_industry: "Suicide Prevention",
  listing_category: "Textline",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Texting",
  listing_age: "Youth & Young Adults",
  listing_population: "LGBTQ & Questioning Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: "1-866-488-7386",
  listing_sms: nil,
  listing_url: "https://www.thetrevorproject.org/get-help-now/",
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United States of America",
  listing_coverage: "National",
})

listing5 = Listing.create({
  listing_name: "Trevor Chat", 
  listing_tagline: "TrevorChat is a free, confidential and secure instant messaging service that provides live help to LGBTQ youth.",
  listing_desc: "Our trained counselors are here to support you 24/7. If you are a young person in crisis, feeling suicidal, or in need of a safe and judgment-free place to talk, call the TrevorLifeline now at 1-866-488-7386.",
  listing_industry: "Suicide Prevention",
  listing_category: "Webchat",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Online",
  listing_age: "Youth & Young Adults",
  listing_population: "LGBTQ & Questioning Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: nil,
  listing_sms: nil,
  listing_url: "https://www.thetrevorproject.org/get-help-now/",
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United States of America",
  listing_coverage: "National",
})

listing6 = Listing.create({
  listing_name: "Trevor Text", 
  listing_tagline: "TrevorChat is a free, confidential and secure instant messaging service that provides live help to LGBTQ youth.",
  listing_desc: "Our trained counselors are here to support you 24/7. If you are a young person in crisis, feeling suicidal, or in need of a safe and judgment-free place to talk, call the TrevorLifeline now at 1-866-488-7386.",
  listing_industry: "Suicide Prevention",
  listing_category: "Textline",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Texting",
  listing_age: "Youth & Young Adults",
  listing_population: "LGBTQ & Questioning Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: nil,
  listing_sms: "678-678",
  listing_url: "https://www.thetrevorproject.org/get-help-now/",
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United States of America",
  listing_coverage: "National",
})

listing7 = Listing.create({
  listing_name: "The Crisis Text Line", 
  listing_tagline: "Crisis Text Line is the free, 24/7, confidential text message service for people in crisis.",
  listing_desc: "The Crisis Text Line is a global not-for-profit organization providing free crisis intervention via SMS message. The organization's services are available 24 hours a day every day, throughout the US by texting 741741, Canada by texting 686868, and the United Kingdom by texting 85258.",
  listing_industry: "Suicide Prevention",
  listing_category: "Textline",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Texting",
  listing_age: "All Ages",
  listing_population: "All Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: nil,
  listing_sms: "686-868",
  listing_url: nil,
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "Canada",
  listing_coverage: "National",
})

listing8 = Listing.create({
  listing_name: "The Crisis Text Line", 
  listing_tagline: "Crisis Text Line is the free, 24/7, confidential text message service for people in crisis.",
  listing_desc: "The Crisis Text Line is a global not-for-profit organization providing free crisis intervention via SMS message. The organization's services are available 24 hours a day every day, throughout the US by texting 741741, Canada by texting 686868, and the United Kingdom by texting 85258.",
  listing_industry: "Suicide Prevention",
  listing_category: "Textline",
  listing_url_to_img: "https://imgur.com/M3VqjRZ.png",
  listing_medium: "Texting",
  listing_age: "All Ages",
  listing_population: "All Individuals",
  listing_language: "English",
  listing_hours: "Open 24/7",
  listing_email: nil,
  listing_phone: nil,
  listing_sms: "85258",
  listing_url: nil,
  listing_address: nil,
  listing_city: nil,
  listing_region: nil,
  listing_country: "United Kingdom",
  listing_coverage: "National",
})

sponsor1.listings.push(listing1, listing2)
sponsor2.listings.push(listing3, listing7, listing8)
sponsor3.listings.push(listing4, listing5, listing6)